// <auto-generated />
using System;
using AISFormations.Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AISFormations.Web.Migrations
{
    [DbContext(typeof(FormationsContext))]
    partial class FormationsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AISFormations.Web.Models.Formation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<DateTime>("DateHeureDebut");

                    b.Property<string>("Description");

                    b.Property<double>("DureeEnHeures");

                    b.Property<bool>("EstActive");

                    b.Property<int>("NombrePlacesDisponibles");

                    b.Property<string>("Presentateur");

                    b.Property<string>("PublicCible");

                    b.Property<string>("Titre");

                    b.HasKey("Id");

                    b.ToTable("Formations");
                });

            modelBuilder.Entity("AISFormations.Web.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Courriel");

                    b.Property<int?>("FormationId");

                    b.Property<int?>("FormationId1");

                    b.HasKey("Id");

                    b.HasIndex("FormationId");

                    b.HasIndex("FormationId1");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("AISFormations.Web.Models.Participant", b =>
                {
                    b.HasOne("AISFormations.Web.Models.Formation")
                        .WithMany("Inscriptions")
                        .HasForeignKey("FormationId");

                    b.HasOne("AISFormations.Web.Models.Formation")
                        .WithMany("ListeAttente")
                        .HasForeignKey("FormationId1");
                });
#pragma warning restore 612, 618
        }
    }
}
